# Statefulset because of persistent /data directory.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "subspace.fullname" . }}
  labels:
    {{- include "subspace.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "subspace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "subspace.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appConfig.httpPort }}
          name: http
        - containerPort: {{ .Values.appConfig.wireguardPort }}
          protocol: UDP
          name: wireguard
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: "SUBSPACE_HTTP_ADDR"
            value: ":{{ .Values.appConfig.httpPort }}"
          - name: "SUBSPACE_LISTENPORT"
            value: "{{ .Values.appConfig.wireguardPort }}"
          - name: "SUBSPACE_HTTP_PREFIX"
            value: "{{ .Values.appConfig.httpPrefix }}"
          {{- toYaml .Values.env | nindent 10 }}
        # livenessProbe:
        #   httpGet:
        #     path: {{ .Values.appConfig.httpPrefix }}/
        #     port: http
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: {{ .Values.appConfig.httpPrefix }}/
        #     port: http
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: data
          mountPath: /data
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.appConfig.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.appConfig.dataVolumeSize }}