# Default values for subspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: finbourne/subspace
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.2"

appConfig:
  # Change WireGuard Listenport
  wireguardPort: 51820
  # Change HTTP UI Listenport
  httpPort: 8080
  # Volume size
  dataVolumeSize: 1Gi
  # Storage class for this PV.
  storageClassName:
  # Optional variable for changing the routing of the server.
  # i.e. a value /something
  # would set the server to listen at http://localhost${SUBSPACE_HTTP_PREFIX}/paths
  # if blank you do not need to put '/'.
  httpPrefix: ""

# Subspace accepts a number of options as
# environment variables.
env:
  - name: "SUBSPACE_HTTP_HOST"
    value: "localhost"
  - name: "SUBSPACE_LETSENCRYPT"
    value: "false"
  - name: "SUBSPACE_HTTP_INSECURE"
    value: "true"
  # Optional variable to change upstream DNS provider 
  - name: "SUBSPACE_NAMESERVER"
    value: "1.1.1.1"  # CoreDNS
  # Optional variables to change IPv4/v6 prefixes
  - name: "SUBSPACE_IPV4_POOL"
    value: "10.99.97.0/24"
  - name: "SUBSPACE_IPV6_POOL"
    value: ""
  # Optional variables to change IPv4/v6 Gateway
  # - name: "SUBSPACE_IPV4_GW"
    # value: "10.99.97.1"
  - name: "SUBSPACE_IPV6_GW"
    value: ""
  # Optional variable to enable or disable IPv6 NAT
  - name: "SUBSPACE_IPV6_NAT_ENABLED"
    value: "0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
